force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>Device</label>
    <nameField>
        <label>Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Landscape_Height__c.field-meta.xml
<CustomField>
    <fullName>Landscape_Height__c</fullName>
    <label>Landscape Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Landscape_Width__c.field-meta.xml
<CustomField>
    <fullName>Landscape_Width__c</fullName>
    <label>Landscape Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Portrait_Height__c.field-meta.xml
<CustomField>
    <fullName>Portrait_Height__c</fullName>
    <label>Portrait Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Portrait_Width__c.field-meta.xml
<CustomField>
    <fullName>Portrait_Width__c</fullName>
    <label>Portrait Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Screen__c/Screen__c.object-meta.xml
<CustomObject>
    <label>Screen</label>
    <nameField>
        <label>Screen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Screen__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>Device</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>Screens</relationshipLabel>
    <relationshipName>Screens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Screen__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <formula>IMAGE( Screenshot_URL__c ,&quot;Image&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Screen__c/fields/Orientation__c.field-meta.xml
<CustomField>
    <fullName>Orientation__c</fullName>
    <label>Orientation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Landscape</fullName>
                <default>true</default>
                <label>Landscape</label>
            </value>
            <value>
                <fullName>Portrait</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Screen__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Screen__c/fields/Screenshot_URL__c.field-meta.xml
<CustomField>
    <fullName>Screenshot_URL__c</fullName>
    <label>Screenshot URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/User_Interaction__c.object-meta.xml
<CustomObject>
    <label>User Interaction</label>
    <nameField>
        <displayFormat>UI-{0000000}</displayFormat>
        <label>User Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Interaction__c/fields/Click_Coordinate_X__c.field-meta.xml
<CustomField>
    <fullName>Click_Coordinate_X__c</fullName>
    <label>Click Coordinate X</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Click_Coordinate_Y__c.field-meta.xml
<CustomField>
    <fullName>Click_Coordinate_Y__c</fullName>
    <label>Click Coordinate Y</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <externalId>true</externalId>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Screen_Height__c.field-meta.xml
<CustomField>
    <fullName>Screen_Height__c</fullName>
    <label>Screen Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Screen_Width__c.field-meta.xml
<CustomField>
    <fullName>Screen_Width__c</fullName>
    <label>Screen Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/User_Session__c.field-meta.xml
<CustomField>
    <fullName>User_Session__c</fullName>
    <label>User Session</label>
    <referenceTo>User_Session__c</referenceTo>
    <relationshipLabel>User Interactions</relationshipLabel>
    <relationshipName>User_Interactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Window_Heigth__c.field-meta.xml
<CustomField>
    <fullName>Window_Heigth__c</fullName>
    <label>Window Heigth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Window_Width__c.field-meta.xml
<CustomField>
    <fullName>Window_Width__c</fullName>
    <label>Window Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Session__c/User_Session__c.object-meta.xml
<CustomObject>
    <label>User Session</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Session__c/fields/Window_Heigth__c.field-meta.xml
<CustomField>
    <fullName>Window_Heigth__c</fullName>
    <label>Window Heigth</label>
    <summarizedField>User_Interaction__c.Window_Heigth__c</summarizedField>
    <summaryForeignKey>User_Interaction__c.User_Session__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Window_Width__c.field-meta.xml
<CustomField>
    <fullName>Window_Width__c</fullName>
    <label>Window Width</label>
    <summarizedField>User_Interaction__c.Window_Width__c</summarizedField>
    <summaryForeignKey>User_Interaction__c.User_Session__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/InteractionNavigationViewerController.cls
public class InteractionNavigationViewerController {
    
    private static String CLICK_EVENT = 'Click';

    @AuraEnabled(cacheable=true)
    public static List<Device__c> getDevicesWithScreens(){
        return [SELECT Id, Portrait_Height__c, Portrait_Width__c, Landscape_Width__c, Landscape_Height__c, Name, 
                    (select Id, Name, Path__c, Screenshot_URL__c, Image__c, Orientation__c from Screens__r order by Name asc) 
                FROM Device__c
                ORDER BY Name ASC];
    }

    @AuraEnabled
    public static List<User_Interaction__c> getUserClicks(String urlPath,Decimal width,Decimal height){
        return [SELECT Id, Click_Coordinate_X__c, Click_Coordinate_Y__c, Window_Width__c, Window_Heigth__c, Screen_Height__c, Screen_Width__c
                FROM User_Interaction__c
                WHERE Type__c =: CLICK_EVENT 
                    AND Path__c LIKE: urlPath+'%' 
                    AND Screen_Width__c =: width
                    AND Screen_Height__c =: height];
    }

    @AuraEnabled
    public static List<User_Interaction__c> getUserClicksBySessionId(String urlPath,Decimal width,Decimal height,String sessionId){
        return [SELECT Id, Click_Coordinate_X__c, Click_Coordinate_Y__c, Window_Width__c, Window_Heigth__c, Screen_Height__c, Screen_Width__c
                FROM User_Interaction__c
                WHERE Type__c =: CLICK_EVENT 
                    AND Path__c LIKE: urlPath+'%' 
                    AND User_Session__c =: sessionId
                    AND Screen_Width__c =: width
                    AND Screen_Height__c =: height];
    }

}