force-app/main/default/objects/User_Interaction__c/User_Interaction__c.object-meta.xml
<CustomObject>
    <label>User Interaction</label>
    <nameField>
        <displayFormat>UI-{0000000}</displayFormat>
        <label>User Interaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Interactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Interaction__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Click_Coordinate_X__c.field-meta.xml
<CustomField>
    <fullName>Click_Coordinate_X__c</fullName>
    <label>Click Coordinate X</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Click_Coordinate_Y__c.field-meta.xml
<CustomField>
    <fullName>Click_Coordinate_Y__c</fullName>
    <label>Click Coordinate Y</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Country_ISO__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO__c</fullName>
    <label>Country ISO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <label>Host</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Impersonated_By__c.field-meta.xml
<CustomField>
    <fullName>Impersonated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Impersonated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Community_Interactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Login_Time__c</fullName>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Login_Url__c.field-meta.xml
<CustomField>
    <fullName>Login_Url__c</fullName>
    <label>Login Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <label>Network ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <externalId>true</externalId>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <label>Query String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Subdivision__c.field-meta.xml
<CustomField>
    <fullName>Subdivision__c</fullName>
    <label>Subdivision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Id__c</fullName>
    <externalId>true</externalId>
    <label>Tracking Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Community_Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/User_Session__c.field-meta.xml
<CustomField>
    <fullName>User_Session__c</fullName>
    <label>User Session</label>
    <referenceTo>User_Session__c</referenceTo>
    <relationshipLabel>User Interactions</relationshipLabel>
    <relationshipName>User_Interactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Window_Heigth__c.field-meta.xml
<CustomField>
    <fullName>Window_Heigth__c</fullName>
    <label>Window Heigth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction__c/fields/Window_Width__c.field-meta.xml
<CustomField>
    <fullName>Window_Width__c</fullName>
    <label>Window Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/User_Interaction_Event__e.object-meta.xml
<CustomObject>
    <label>User Interaction Event</label>
    <pluralLabel>USer Interaction Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/User_Interaction_Event__e/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <label>Browser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Click_Coordinate_X__c.field-meta.xml
<CustomField>
    <fullName>Click_Coordinate_X__c</fullName>
    <label>Click Coordinate X</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Click_Coordinate_Y__c.field-meta.xml
<CustomField>
    <fullName>Click_Coordinate_Y__c</fullName>
    <label>Click Coordinate Y</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Country_ISO__c.field-meta.xml
<CustomField>
    <fullName>Country_ISO__c</fullName>
    <label>Country ISO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <label>Host</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Impersonated_ById__c.field-meta.xml
<CustomField>
    <fullName>Impersonated_ById__c</fullName>
    <label>Impersonated ById</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Impersonated_Session__c.field-meta.xml
<CustomField>
    <fullName>Impersonated_Session__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Impersonated Session</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Login_Time__c</fullName>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Login_Url__c.field-meta.xml
<CustomField>
    <fullName>Login_Url__c</fullName>
    <label>Login Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Network_ID__c.field-meta.xml
<CustomField>
    <fullName>Network_ID__c</fullName>
    <label>Network ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Query_String__c.field-meta.xml
<CustomField>
    <fullName>Query_String__c</fullName>
    <label>Query String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Source_IP__c.field-meta.xml
<CustomField>
    <fullName>Source_IP__c</fullName>
    <label>Source IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Subdivision__c.field-meta.xml
<CustomField>
    <fullName>Subdivision__c</fullName>
    <label>Subdivision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Id__c</fullName>
    <label>Tracking Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interaction_Event__e/fields/Window_Heigth__c.field-meta.xml
<CustomField>
    <fullName>Window_Heigth__c</fullName>
    <label>Window Heigth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Session__c/User_Session__c.object-meta.xml
<CustomObject>
    <label>User Session</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Session__c/fields/Browser__c.field-meta.xml
<CustomField>
    <fullName>Browser__c</fullName>
    <label>Browser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Impersonated_By__c.field-meta.xml
<CustomField>
    <fullName>Impersonated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Impersonated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Impersonated_Session__c.field-meta.xml
<CustomField>
    <fullName>Impersonated_Session__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Impersonated Session</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Login_Url__c.field-meta.xml
<CustomField>
    <fullName>Login_Url__c</fullName>
    <label>Login Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <label>Network Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Source_IP__c.field-meta.xml
<CustomField>
    <fullName>Source_IP__c</fullName>
    <label>Source IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Session__c/fields/Window_Heigth__c.field-meta.xml
<CustomField>
    <fullName>Window_Heigth__c</fullName>
    <label>Window Heigth</label>
    <summarizedField>User_Interaction__c.Window_Heigth__c</summarizedField>
    <summaryForeignKey>User_Interaction__c.User_Session__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/UserInteractionTriggerEventHandler.cls
public without sharing class UserInteractionTriggerEventHandler {
    
    public static void handleAfterInsert(List<User_Interaction_Event__e> newEvents){

        Set<String> trackingIds = new Set<String>();
        Map<String,Id> userSessionTrackingMap = new Map<String,Id>();

        Map<String,User_Session__c> newUserSessionsMap = new Map<String,User_Session__c>();
        List<User_Interaction__c> newInteractions = new List<User_Interaction__c>();

        for(User_Interaction_Event__e uie : newEvents){ trackingIds.add(uie.Tracking_Id__c); }

        List<User_Session__c> existingSessions = [SELECT ID, Tracking_Id__c FROM User_Session__c WHERE Tracking_Id__c IN :trackingIds];

        for(User_Session__c us : existingSessions){ userSessionTrackingMap.put(us.Tracking_Id__c,us.Id); }

        for(User_Interaction_Event__e uie : newEvents){
            User_Interaction__c newUserInteraction = buildUserInteraction(uie);

            if(userSessionTrackingMap.containsKey(uie.Tracking_Id__c)){//SESSION ALREADY EXIST
                newUserInteraction.User_Session__c = userSessionTrackingMap.get(uie.Tracking_Id__c);
            }else{//NEW SESSION
                User_Session__c newUserSession = buildUserSession(uie);
                newUserSessionsMap.put(uie.Tracking_Id__c,newUserSession);
            }

            newInteractions.add(newUserInteraction);

        }

        if(!newUserSessionsMap.values().isEmpty()){ insert newUserSessionsMap.values(); }//INSERT NEW SESSIONS


        for(User_Interaction__c ui : newInteractions){//ASSOCIATE NEW INTERACTIONS WITH THE NEW SESSIONS JUST CREATED
            if(newUserSessionsMap.containsKey(ui.Tracking_Id__c)){ ui.User_Session__c = newUserSessionsMap.get(ui.Tracking_Id__c).Id; }
        }

        if(!newInteractions.isEmpty()){ insert newInteractions; }

    }

    private static User_Interaction__c buildUserInteraction(User_Interaction_Event__e uie){
        User_Interaction__c ui = new User_Interaction__c();
        ui.Click_Coordinate_X__c = uie.Click_Coordinate_X__c;
        ui.Click_Coordinate_Y__c = uie.Click_Coordinate_Y__c;
        ui.Host__c = uie.Host__c;
        ui.Origin__c = uie.Origin__c;
        ui.Path__c = uie.Path__c;
        ui.Query_String__c = uie.Query_String__c;
        ui.Timestamp__c = uie.Timestamp__c;
        ui.Type__c = uie.Type__c;
        ui.URL__c = uie.URL__c;
        ui.Tracking_Id__c = uie.Tracking_Id__c;

        //REDUNDANT FIELDS
        ui.Application__c = uie.Application__c;
        ui.Browser__c = uie.Browser__c;
        ui.City__c = uie.City__c;
        ui.Country_ISO__c = uie.Country_ISO__c;
        ui.Impersonated_By__c = uie.Impersonated_ById__c;
        ui.Impersonated_Session__c = uie.Impersonated_Session__c;
        ui.Coordinates__Longitude__s = uie.Longitude__c;
        ui.Coordinates__Latitude__s = uie.Latitude__c;
        ui.Login_Time__c = uie.Login_Time__c;
        ui.Login_Url__c = uie.Login_Url__c;
        ui.Network_Id__c = uie.Network_ID__c;
        ui.Platform__c = uie.Platform__c;
        ui.PostalCode__c = uie.PostalCode__c;
        ui.Source_IP__c = uie.Source_IP__c;
        ui.Subdivision__c = uie.Subdivision__c;
        ui.User__c = uie.User_ID__c;
        ui.Window_Heigth__c = uie.Window_Heigth__c;
        ui.Window_Width__c = uie.Window_Width__c;
        return ui;
    } 

    private static User_Session__c buildUserSession(User_Interaction_Event__e uie){
        User_Session__c us = new User_Session__c();
        us.Application__c = uie.Application__c;
        us.Browser__c = uie.Browser__c;
        us.City__c = uie.City__c;
        us.Coordinates__Longitude__s = uie.Longitude__c;
        us.Coordinates__Latitude__s = uie.Latitude__c;
        us.Country_ISO__c = uie.Country_ISO__c;
        us.Impersonated_By__c = uie.Impersonated_ById__c;
        us.Impersonated_Session__c = uie.Impersonated_Session__c;
        us.Login_Time__c = uie.Login_Time__c;
        us.Tracking_Id__c = uie.Tracking_Id__c;
        us.Login_Url__c = uie.Login_Url__c;
        us.Network_Id__c = uie.Network_ID__c;
        us.Platform__c = uie.Platform__c;
        us.Postal_Code__c = uie.PostalCode__c;
        us.Source_IP__c = uie.Source_IP__c;
        us.Sub_Division__c = uie.Subdivision__c;
        us.User__c = uie.User_ID__c;
        //us.Window_Heigth__c = uie.Window_Heigth__c;
        //us.Window_Width__c = uie.Window_Width__c;
        return us;
    }

}